name: teacher
description: 教师端应用
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0
  flutter_localizations:
    sdk: flutter
  
  # 状态管理
  provider: ^6.0.5
  
  # 本地存储
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  
  # 网络请求
  http: ^1.1.0
  
  # JSON序列化
  json_annotation: ^4.8.1
  
  # UI组件
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  
  # 图表
  fl_chart: ^0.66.0
  
  # 工具类
  intl: ^0.18.1
  uuid: ^4.2.1
  path: ^1.8.0
  # 哈希校验（在线升级安装包 MD5）
  crypto: ^3.0.3
  
  
  # 窗口管理
  window_manager: ^0.3.7
  
  # 后端服务 (用于打包)
  shelf: ^1.4.1
  shelf_router: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/